# The config.nix
# This is where my NIX variant of all configurations lies here
# Some configurations are auto-generated by a program
# and not need to put here
let
    fastfetch = import ./config/fastfetch.nix;
in
{
    "fastfetch/config.jsonc".text = builtins.toJSON fastfetch;
}